name: Deploy to VPS

on:
  push:
    branches:
      - main # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROPLAYAS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H srv830182.hstgr.cloud >> ~/.ssh/known_hosts

      - name: Rsync files to VPS
        run: |
          rsync -az --delete --exclude="node_modules" --exclude=".next" --exclude=".env" ./ redproplayas@srv830182.hstgr.cloud:/home/redproplayas/web/proplayas.org/frontend/

      - name: Install dependencies & Build on VPS
        run: |
          ssh redproplayas@srv830182.hstgr.cloud << 'ENDSSH'
            cd /home/redproplayas/web/proplayas.org/frontend
            npm install --omit=dev
            npm run build
            pm2 reload proplayas-frontend || pm2 start npm --name "proplayas-frontend" -- start
          ENDSSH
